PROGRAM MENCARI_LUAS_LINGKARAN;
USES CRT;

CONST
  PHI = 3.14;

VAR
  JARI  : INTEGER;
  LUAS, KEL : REAL;

BEGIN
  WRITELN('MENCARI LUAS LINGKARAN');
  WRITELN('======================');
  WRITE('MASUKAN BERAPA JARI-JARI ... =');
  READLN(JARI);

  LUAS  := PHI * JARI * JARI;
  KEL   := 2 * PHI * JARI;

  WRITELN('HASIL LUAS LINGKARAN DARI JARI-JARI', JARI, 'ADALAH : ', LUAS:6:2);
  WRITELN('HASIL KELILING : ', KEL:6:2);

  READLN;
END.
